package studio;

import java.util.*;

/**
 * Translates the engine's Spanish messages to English when STUDIO_LANG=en.
 * Works on fragments so messages built by concatenation are covered too.
 */
final class Msg {
	private static final boolean EN = "en".equals(System.getenv("STUDIO_LANG"));
	private static final List<String[]> PAIRS = new ArrayList<>();

	private static void p(String es, String en) {
		PAIRS.add(new String[] { es, en });
	}

	static {
		// errors
		p("El proyecto está abierto en otra aplicación (¿Ghidra clásico?)", "The project is open in another application (classic Ghidra?)");
		p("Solo se pueden editar estructuras y uniones del programa", "Only the program's structures and unions can be edited");
		p("Espera a que termine el análisis para deshacer", "Wait for analysis to finish before undoing");
		p("Espera a que termine el análisis para rehacer", "Wait for analysis to finish before redoing");
		p("Cierra el programa antes de renombrarlo", "Close the program before renaming it");
		p("Cierra el programa antes de borrarlo", "Close the program before deleting it");
		p("Cierra el programa antes de moverlo", "Close the program before moving it");
		p("Hay programas abiertos en esa carpeta", "There are open programs in that folder");
		p("La instrucción no tiene ninguna constante", "The instruction has no constant");
		p(" con ese valor", " with that value");
		p("La variable no tiene uso en el código", "The variable is not used in the code");
		p("No se pudo inferir ninguna estructura para «", "Couldn't infer a structure for «");
		p("No se pudo iniciar el descompilador: ", "Couldn't start the decompiler: ");
		p("No hay ningún proyecto .gpr en ", "There is no .gpr project in ");
		p("No hay ningún programa abierto", "No program is open");
		p("No hay ningún proyecto abierto", "No project is open");
		p("No hay ninguna instrucción en ", "There is no instruction at ");
		p("No hay ninguna función en ", "There is no function at ");
		p("No se encontró la variable «", "Variable not found «");
		p("No se encontró «", "Not found «");
		p("No se pudo crear la función", "Couldn't create the function");
		p("No se pudo desensamblar", "Couldn't disassemble");
		p("No se pueden comparar: ", "Can't compare: ");
		p("No es un proyecto de Ghidra: ", "Not a Ghidra project: ");
		p("No existe la carpeta ", "Folder doesn't exist: ");
		p("No existe el bloque ", "Block doesn't exist: ");
		p("No existe el tipo ", "Type doesn't exist: ");
		p("No existe: ", "Doesn't exist: ");
		p("No existe ", "Doesn't exist: ");
		p("No es un enum", "Not an enum");
		p("Ghidra no reconoce el formato de ", "Ghidra doesn't recognize the format of ");
		p("Bytes hexadecimales inválidos: ", "Invalid hex bytes: ");
		p("Dirección inválida: ", "Invalid address: ");
		p("Error al descompilar: ", "Decompilation error: ");
		p("La exportación falló: ", "Export failed: ");
		p("Método desconocido: ", "Unknown method: ");
		p("Tipo de script no soportado: ", "Unsupported script type: ");
		p("Tipo desconocido: ", "Unknown type: ");
		p("Exportador desconocido: ", "Unknown exporter: ");
		p("Inicia el emulador primero", "Start the emulator first");
		p("Ya existe un proyecto «", "A project named «");
		p("» en esa carpeta", "» already exists in that folder");
		p("El equate «", "Equate «");
		p("» ya existe con otro valor", "» already exists with a different value");
		p("El programa ", "Program ");
		p(" no está abierto", " is not open");
		p("Falta el parámetro «", "Missing parameter «");
		p("Namespace desconocido", "Unknown namespace");
		// progress & emulator
		p("Importando ", "Importing ");
		p("Abriendo ", "Opening ");
		p("Analizando…", "Analyzing…");
		p("La función ha retornado", "The function has returned");
		p("Punto de ruptura en ", "Breakpoint at ");
		p("pasos alcanzado", "steps reached");
		p("Límite de ", "Limit of ");
		p("Listo en ", "Ready at ");
		p("Detenido", "Stopped");
		p("Paso ", "Step ");
		p(" más)", " more)");
		p("No hay nada seleccionado", "Nothing is selected");
		p("Estado del depurador", "Debugger state");
		p("Selección desconocida: ", "Unknown selection: ");
		// undo names (longest first matters for prefixes)
		p("Aplicar archivo de tipos", "Apply Type Archive");
		p("Comentario de función", "Function Comment");
		p("Opciones de análisis", "Analysis Options");
		p("Permisos de bloque", "Block Permissions");
		p("Renombrar variable", "Rename Variable");
		p("Renombrar bloque", "Rename Block");
		p("Renombrar tipo", "Rename Type");
		p("Aplicar nombres", "Apply Names");
		p("Añadir referencia", "Add Reference");
		p("Quitar referencia", "Remove Reference");
		p("Crear estructura", "Create Structure");
		p("Quitar marcador", "Remove Bookmark");
		p("Parchear bytes", "Patch Bytes");
		p("Borrar etiqueta", "Delete Label");
		p("Crear etiqueta", "Create Label");
		p("Borrar función", "Delete Function");
		p("Crear función", "Create Function");
		p("Añadir bloque", "Add Block");
		p("Borrar bloque", "Delete Block");
		p("Añadir campo", "Add Field");
		p("Borrar campo", "Delete Field");
		p("Editar campo", "Edit Field");
		p("Añadir valor", "Add Value");
		p("Borrar código", "Clear Code");
		p("Borrar tipo", "Delete Type");
		p("Cambiar tipo", "Change Type");
		p("Crear typedef", "Create Typedef");
		p("Crear unión", "Create Union");
		p("Crear enum", "Create Enum");
		p("Definir dato", "Define Data");
		p("Desensamblar", "Disassemble");
		p("Editar firma", "Edit Signature");
		p("Auto-análisis", "Auto-analysis");
		p("Importar C", "Import C");
		p("Ensamblar", "Assemble");
		p("Comentario", "Comment");
		p("Marcador", "Bookmark");
		p("Renombrar", "Rename");
		// second batch
		p("Registro desconocido: ", "Unknown register: ");
		p("No hay ningún dato en ", "There is no data at ");
		p("Coloca el cursor sobre una variable", "Place the cursor on a variable");
		p("Token desconocido", "Unknown token");
		p("No es una estructura: ", "Not a structure: ");
		p("No hay ningún campo en el offset ", "There is no field at offset ");
		p("Ya hay un análisis en marcha", "An analysis is already running");
		p("Analizador desconocido: ", "Unknown analyzer: ");
		p("Cargador desconocido: ", "Unknown loader: ");
		p("Solo disponible para estructuras", "Only available for structures");
		p("Añadir etiqueta de función", "Add Function Tag");
		p("Quitar etiqueta de función", "Remove Function Tag");
		p("Añadir campo de bits", "Add Bit Field");
		p("Tamaño de estructura", "Structure Size");
		p("Valor de registro", "Register Value");
		p("Formato de dato", "Data Format");
		p("Definir cadena", "Define String");
		p("Editar función", "Edit Function");
		p("Editar variable", "Edit Variable");
		p("Renombrar campo", "Rename Field");
		p("Insertar campo", "Insert Field");
		p("Importar tipos", "Import Types");
		p("Dividir bloque", "Split Block");
		p("Unir bloques", "Merge Blocks");
		p("Mover bloque", "Move Block");
		p("Mover campo", "Move Field");
		p("Forzar firma", "Override Signature");
		p("Quitar valor", "Remove Value");
		p("Crear array", "Create Array");
		p("Cargar PDB", "Load PDB");
		p("Empaquetado", "Packing");
		p("Alineación", "Alignment");
		p("Ancho máximo de línea", "Maximum line width");
		p("Ancho de sangría", "Indent width");
		p("Eliminar código inalcanzable", "Eliminate unreachable code");
		p("Simplificar aritmética de doble precisión", "Simplify double-precision arithmetic");
		p("Ocultar conversiones de tipo (casts)", "Hide type casts");
		p("Mostrar la convención de llamada", "Print calling convention");
		p("Inferir punteros a partir de constantes", "Infer pointers from constants");
		p("Reconstruir bucles for", "Recover for-loops");
		p("Respetar memoria de solo lectura", "Respect read-only memory");
		p("Mostrar comentarios previos", "Show pre comments");
		p("Mostrar comentarios de cabecera", "Show plate comments");
		p("Mostrar comentarios de fin de línea", "Show end-of-line comments");
		p("Mostrar comentarios posteriores", "Show post comments");
		p("Mostrar avisos del descompilador", "Show decompiler warnings");
		p("Mostrar comentario de la función", "Show function header comment");
		p("Formato de los enteros", "Integer format");
		p("Mostrar namespaces", "Namespace display");
		p("Estilo de los comentarios", "Comment style");
		// BSim, Version Tracking, Ghidra Server, extensions, Python
		p("Ya existe una base de datos BSim con ese nombre", "A BSim database with that name already exists");
		p("El programa no tiene funciones con cuerpo", "The program has no functions with a body");
		p("Consultando la base de datos…", "Querying the database…");
		p("No hay ninguna sesión de Version Tracking abierta", "No Version Tracking session is open");
		p("El programa origen y el destino no pueden ser el mismo", "Source and destination programs can't be the same");
		p("Ya existe un archivo con ese nombre en la carpeta", "A file with that name already exists in the folder");
		p("No se encontraron los programas de la sesión en el proyecto", "The session's programs were not found in the project");
		p("No se encontró la coincidencia ", "Match not found: ");
		p("Hace falta una función en el origen y otra en el destino", "A function is needed in both source and destination");
		p("No se pudo conectar con el servidor", "Couldn't connect to the server");
		p("Este servidor no permite cambiar la contraseña", "This server doesn't allow changing the password");
		p("El servidor rechazó la nueva contraseña", "The server rejected the new password");
		p("El proyecto no es compartido", "The project is not shared");
		p("Cierra el programa antes de cambiar su estado de versiones", "Close the program before changing its version state");
		p("No se pudo hacer el check-out: otro usuario lo tiene en exclusiva", "Couldn't check out: another user has it exclusively");
		p("Otro usuario ha subido una versión nueva y tú también has modificado el archivo: esa fusión solo se puede hacer en Ghidra clásico",
			"Another user checked in a new version and you also modified the file: that merge can only be done in classic Ghidra");
		p("El programa es de solo lectura: haz check-out para poder guardar los cambios", "The program is read-only: check it out to save changes");
		p("No es una extensión de Ghidra: ", "Not a Ghidra extension: ");
		p("La extensión «", "Extension «");
		p("» ya está instalada", "» is already installed");
		p("No se pudo instalar la extensión «", "Couldn't install extension «");
		p("Esta extensión viene con Ghidra y no se puede desinstalar", "This extension ships with Ghidra and can't be uninstalled");
		p("No se pudo cambiar el estado de la extensión", "Couldn't change the extension's state");
		p("No existe la extensión ", "Extension doesn't exist: ");
		p("Python no está disponible: el motor no se inició con PyGhidra", "Python is not available: the engine wasn't started with PyGhidra");
		p("Esta variable no se puede dividir: no agrupa varios usos distintos", "This variable can't be split: it doesn't merge several distinct uses");
		p("Ya existe una variable con ese nombre en la función", "A variable with that name already exists in the function");
		p("Dividir variable", "Split Variable");
		p("Ya existe una base de datos Function ID con ese nombre", "A Function ID database with that name already exists");
		p("No es una base de datos Function ID válida: ", "Not a valid Function ID database: ");
		p("Las bases de datos incluidas con Ghidra no se pueden quitar", "The databases shipped with Ghidra can't be removed");
		p("Las bases de datos incluidas con Ghidra son de solo lectura", "The databases shipped with Ghidra are read-only");
		p("Elige al menos un programa", "Choose at least one program");
		p("Todos los programas deben tener el mismo procesador", "All programs must have the same processor");
		p("Cancelado", "Cancelled");
		p("La dirección ya está dentro del bloque", "The address is already inside the block");
		p("Símbolo desconocido", "Unknown symbol");
		p("No se puede borrar: el namespace no está vacío o el símbolo es automático", "Can't delete: the namespace is not empty or the symbol is automatic");
		p("Coloca el cursor sobre un campo de una unión", "Place the cursor on a field of a union");
		p("No se pudo identificar la operación de forma única", "Couldn't identify the operation uniquely");
		p("El rango es demasiado grande", "The range is too large");
		p("El proyecto ya es compartido", "The project is already shared");
		p("El proyecto no admite la conversión", "The project can't be converted");
		p("Función desconocida", "Unknown function");
		p("Cambiar dirección base", "Set Image Base");
		p("Expandir bloque", "Expand Block");
		p("Crear clase", "Create Class");
		p("Crear namespace", "Create Namespace");
		p("Convertir en clase", "Convert to Class");
		p("Mover símbolo", "Move Symbol");
		p("Borrar símbolo", "Delete Symbol");
		p("Enlazar librería externa", "Link External Library");
		p("Editar ubicación externa", "Edit External Location");
		p("Aplicar diferencias", "Apply Differences");
		p("Fijar parámetros y retorno", "Commit Params/Return");
		p("Fijar nombres de variables locales", "Commit Local Names");
		p("Forzar campo de unión", "Force Union Field");
		p("Definir variable de pila", "Define Stack Variable");
		p("Borrar variable de pila", "Clear Stack Variable");
		p("Tamaño del marco de pila", "Stack Frame Size");
		p("Definición de función", "Function Definition");
		p("(sin campo)", "(no field)");
		p("El programa no indica qué PDB le corresponde", "The program doesn't say which PDB belongs to it");
		p("El servidor de símbolos no tiene ", "The symbol server doesn't have ");
		p("No hay más en esa dirección", "Nothing more in that direction");
		p("Borrar con opciones", "Clear With Options");
		p("Borrar flujo y reparar", "Clear Flow and Repair");
		p("No hay un dato definido en ", "There is no defined data at ");
		p("Ajustes del dato", "Data Settings");
		p("Ajuste desconocido: ", "Unknown setting: ");
		p("Grupo desconocido: ", "Unknown group: ");
		p("Parchear dato", "Patch Data");
		p("Ese tipo de dato no se puede escribir así", "That data type can't be written that way");
		p("Quitar equate", "Remove Equate");
		p("Aplicar enum", "Apply Enum");
		p("Formato desconocido: ", "Unknown format: ");
		p("No hay ninguna etiqueta «", "There is no label «");
		p("Etiqueta primaria", "Set Primary Label");
		p("Fijar etiqueta", "Pin Label");
		p("Punto de entrada", "Entry Point");
		p("Tipo de referencia desconocido: ", "Unknown reference type: ");
		p("Clase de referencia desconocida: ", "Unknown reference class: ");
		p("Etiqueta del operando", "Operand Label");
		p("Recrear función", "Re-create Function");
		p("Crear funciones", "Create Functions");
		p("Función thunk", "Thunk Function");
		p("No hay función en ", "There is no function at ");
		p("Almacenamiento inválido: ", "Invalid storage: ");
		p("Almacenamiento del parámetro", "Parameter Storage");
		p("Cambio de profundidad de pila", "Stack Depth Change");
		p("Etiquetas de función", "Function Tags");
		p("No hay una instrucción en ", "There is no instruction at ");
		p("Modificar flujo de la instrucción", "Modify Instruction Flow");
		p("Longitud de la instrucción", "Instruction Length");
		p("Editar bloque de memoria", "Edit Memory Block");
		p("Color de fondo", "Background Color");
		p("Opciones del programa", "Program Options");
		p("Esa opción no se puede cambiar desde aquí", "That option can't be changed from here");
		p("Árbol del programa", "Program Tree");
		p("El fragmento tiene código: muévelo a otro antes de borrarlo", "The fragment has code: move it to another one before deleting it");
		p("Acción desconocida: ", "Unknown action: ");
		p("Componente inexistente", "No such component");
		p("Cambiar lenguaje", "Set Language");
		p("Añadida", "Added");
		p("Quitada", "Removed");
		p("Renombrada", "Renamed");
		p("Símbolo externo", "External symbol");
		p("Renombrar espacio overlay", "Rename Overlay Space");
		p("Categoría de tipos", "Type Category");
		p("La categoría raíz no se puede borrar", "The root category can't be deleted");
		p("Tipos de datos", "Data Types");
		p(" no es un enum", " is not an enum");
		p(" no es una estructura", " is not a structure");
		p("Solo se desempaquetan arrays y estructuras", "Only arrays and structures can be unpacked");
		p("Leer cabeceras de C", "Parse C Headers");
		p("No existe el archivo de tipos ", "There is no type archive ");
		p("Ya existe ", "Already exists: ");
		p("No existe la categoría ", "There is no category ");
		p("La arquitectura del programa se cambia con «Cambiar lenguaje»", "The program's architecture is changed with “Set Language”");
		p("El programa no tiene tipos de ese archivo", "The program has no types from that archive");
		p("Asociar tipos", "Associate Types");
		p("Copiar tipos", "Copy Types");
		p("Crear enum a partir de otros", "Create Enum From Others");
		p("Duplicar campo", "Duplicate Field");
		p("Desempaquetar campo", "Unpack Field");
		p("Array flexible", "Flexible Array");
		p("Sincronizar tipos", "Synchronize Types");
		p("Arquitectura", "Architecture");
		p("Coloca el cursor sobre una constante", "Place the cursor on a constant");
		p("Esa constante no se puede identificar de forma estable", "That constant can't be identified in a stable way");
		p("Ya existe un equate «", "There is already an equate «");
		p("» con otro valor", "» with another value");
		p("Cambiar tipo de retorno", "Retype Return");
		p("Cambiar tipo del campo", "Retype Field");
		p("Ajustar offset del puntero", "Adjust Pointer Offset");
		p("Extensión de especificación", "Specification Extension");
		p("Quitar extensión de especificación", "Remove Specification Extension");
		p("(indirecta)", "(indirect)");
		p("Aplicar de la otra función", "Apply From Other Function");
		p("El descompilador no devolvió características: ", "The decompiler returned no features: ");
		p("La función es demasiado pequeña para Function ID", "The function is too small for Function ID");
		p("Hash hexadecimal inválido: ", "Invalid hexadecimal hash: ");
		p("Elemento desconocido", "Unknown item");
		p("Traducir cadenas", "Translate Strings");
		p("Tamaño inválido", "Invalid size");
		p("No existe el archivo fuente ", "There is no source file ");
		p("fuera", "outside");
		p("Añadir al programa", "Add To Program");
		p("Ningún cargador puede añadir ese archivo a este programa", "No loader can add that file to this program");
		p("Valor inválido para «", "Invalid value for «");
		p("Ese elemento no admite enlaces", "That item does not support links");
		p("Ese archivo no tapa a uno versionado", "That file does not hide a versioned one");
		p("No existe la configuración ", "There is no configuration ");
		p("Ubicación no reconocida: ", "Unrecognized location: ");
		p("La carpeta local de símbolos no es válida: ", "The local symbols folder is not valid: ");
		p("Solo se pueden cambiar los scripts de tu carpeta de scripts", "Only scripts in your scripts folder can be changed");
		p("No se pudo borrar ", "Couldn't delete ");
		p("No se pudo renombrar ", "Couldn't rename ");
		p("Los directorios de Ghidra no se pueden quitar; desactívalo", "Ghidra's directories can't be removed; disable it");
		p("No es un archivo SARIF: falta «runs»", "Not a SARIF file: “runs” is missing");
		p("No es una URL de Ghidra: ", "Not a Ghidra URL: ");
		p("No existe la tabla ", "There is no table ");
		p("Expresión inválida", "Invalid expression");
		p("Hilo ", "Thread ");
		p("Python no está disponible", "Python is not available");
		p("La importación por lotes ya no existe: ", "The batch import no longer exists: ");
		p("sin especificación de carga para ", "no load specification for ");
		p("No es un contenedor: ", "Not a container: ");
		p("No es un kernel de iOS con extensiones enlazadas (prelinked): ", "Not an iOS kernel with prelinked extensions: ");
		p("El contenedor no tiene extensiones del kernel (.kext)", "The container has no kernel extensions (.kext)");
		p("Hace falta un descompilador de Java: elige el ejecutable de JAD o el .jar de CFR", "A Java decompiler is needed: choose the JAD executable or the CFR .jar");
		p(": se agotó el tiempo", ": timed out");
		p(": salida ", ": exit status ");
		p("No es un archivo JAR: ", "Not a JAR file: ");
		p("El archivo saldría de la carpeta de destino: ", "The file would end up outside the destination folder: ");
		p("No es un APK: ", "Not an APK: ");
		p("No hay ningún campo de una estructura o unión en ", "There is no structure or union field at ");
		p("El lenguaje del programa no es de Sleigh", "The program's language is not a Sleigh language");
		p("No se puede ensamblar «", "Cannot assemble «");
		p("(valor)", "(value)");
		p("La edición de la estructura ya no existe", "The structure editing session no longer exists");
		p("El campo ya está en el extremo", "The field is already at the end");
		p("Operación desconocida: ", "Unknown operation: ");
		p("No se encuentra el ejecutable de CTADL. Instálalo (pip install ctadl) y elige dónde está.", "The CTADL executable was not found. Install it (pip install ctadl) and choose where it is.");
		p("Falta el script ExportPCodeForCTADL.java de Ghidra", "Ghidra's ExportPCodeForCTADL.java script is missing");
		p("CTADL terminó con error ", "CTADL ended with error ");
		p("No se pudo exportar el p-code: ", "The p-code could not be exported: ");
		p("Exportando el p-code", "Exporting the p-code");
		p("Indexando con CTADL", "Indexing with CTADL");
		p("Consultando con CTADL", "Querying with CTADL");
		p("Este programa todavía no tiene índice de CTADL: créalo primero", "This program has no CTADL index yet: create it first");
		p("No existe el archivo de consulta ", "The query file does not exist: ");
		p("Marca al menos una fuente o un sumidero", "Mark at least one source or sink");
		p("Error al descompilar ", "Error decompiling ");
		p("No se pudo conectar con el servidor: ", "Could not connect to the server: ");
		p("El servidor pide usuario y contraseña para esa URL", "The server asks for a user and password for that URL");
		p("La URL no lleva a ningún archivo (", "The URL does not lead to any file (");
		p("La URL lleva a una carpeta, no a un programa", "The URL leads to a folder, not a program");
		p("El archivo de la URL no es un programa: ", "The file of the URL is not a program: ");
		PAIRS.sort((a, b) -> b[0].length() - a[0].length());
	}

	private Msg() {
	}

	static String t(String s) {
		if (!EN || s == null) {
			return s;
		}
		String out = s;
		for (String[] pair : PAIRS) {
			if (out.contains(pair[0])) {
				out = out.replace(pair[0], pair[1]);
			}
		}
		return out;
	}
}
